[package]
name = "garagedoor-bootloader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "garagedoor-bootloader"
path = "src/main.rs"

[dependencies]
embassy-rp = { workspace = true, features = ["rp2040", "critical-section-impl"] }
embassy-boot-rp = { workspace = true }
embassy-boot = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
defmt = { workspace = true }
defmt-rtt = { workspace = true }
garagedoor-core = { workspace = true }
